### PR TITLE
Server configuration improvements

### PR DESCRIPTION
**Pull request by RobiNino**
- [x] All [tests](https://github.com/jfrog/setup-jfrog-cli#build-the-code) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----
Note:
- The internal `setup-jfrog-cli-server` server ID will no longer be available. Set a custom server ID if you need to reference the server directly.

Improvements:
- Support custom server ID
- Unique default server ID for each run of a workflow
- Support multiple configurations

Bug fix:
- Only remove server IDs configured in the specific workflow (should fix https://github.com/jfrog/setup-jfrog-cli/issues/94#issuecomment-2440135410)

### CODE REVIEW

**Comment by sverdlov93** [comment]
> Unique default server ID for each run of a workflow

breaking change? if someone used the old one?

**Comment by RobiNino** [comment]
The pervious server ID was never documented, using it directly was as using an internal code. I can add the breaking change label if you think it necessary but I'm not sure this actually counts as one.

**Comment by sverdlov93** [comment]
> The pervious server ID was never documented, using it directly was as using an internal code. I can add the breaking change label if you think it necessary but I'm not sure this actually counts as one.

https://github.com/search?q=%22setup-jfrog-cli-server%22+language%3AYAML&type=code&l=YAML

**Review by eyalbe4 — APPROVED** [review]

**Comment by JackCoplandGranta** [comment]
The readme does explicitly mentions this server id (and is now presumably incorrect?):
image

**Comment by tgharold** [comment]
As a user, we consider this to be a breaking change and our workflows are failing because of it.

**Comment by hazeltonl** [comment]
> As a user, we consider this to be a breaking change and our workflows are failing because of it. We'd have been okay if you had provided a migration path (add the new input in 4.5, then remove the current default in 5.0).

This may be a good opportunity to look at my Pull Request? It would potentially address this scenario where users inherit breaking changes when only the minor version has been updated. I assume only JFrog employee are able to add reviewers to PRs @RobiNino @eyalbe4
https://github.com/jfrog/setup-jfrog-cli/pull/228

**Comment by aairey** [comment]
> > Unique default server ID for each run of a workflow
> 
> breaking change? if someone used the old one?

BREAKING CHANGE indeed
Workflows started failing here.

**Comment by RobiNino** [comment]
Hi all,
We sincerely apologize for the inconvenience caused by this error on our part. 
We have just released extension version v4.5.1, which restores the default server ID while also providing the option to set a custom server ID. 
Thank you for your understanding and patience.

**Pull request merged**
